name: discord-diffusion
channels:
  - pytorch
  - defaults
  - nvidia/label/cuda-11.7.0
dependencies:
  - cuda-toolkit
  - pip=20.3
  - python=3.8.5
  - pytorch=1.13.1
  - pytorch-cuda
  - torchvision
  - requests
  - pip:
    - -r file:requirements.txt